In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.randn(4,3)
data

array([[-0.31932173, -0.79304011, -1.23790005],
       [-1.0166796 ,  2.5692134 ,  0.11449653],
       [ 0.09013173,  1.87581295,  0.38772829],
       [ 0.61422017, -0.86891757,  1.1609854 ]])

In [3]:
df = pd.DataFrame(data,index=["Kadir","Ozge","Atil","Ada"],columns=["Salary","Age","Seniority"])
df

         Salary       Age  Seniority
Kadir -0.319322 -0.793040  -1.237900
Ozge  -1.016680  2.569213   0.114497
Atil   0.090132  1.875813   0.387728
Ada    0.614220 -0.868918   1.160985

In [4]:
df.loc["Atil"]["Age"] = 47

In [5]:
df

         Salary        Age  Seniority
Kadir -0.319322  -0.793040  -1.237900
Ozge  -1.016680   2.569213   0.114497
Atil   0.090132  47.000000   0.387728
Ada    0.614220  -0.868918   1.160985

In [6]:
df.iloc[:,1]

Kadir    -0.793040
Ozge      2.569213
Atil     47.000000
Ada      -0.868918
Name: Age, dtype: float64

In [7]:
df["Extra"] = 50

In [8]:
df

         Salary        Age  Seniority  Extra
Kadir -0.319322  -0.793040  -1.237900     50
Ozge  -1.016680   2.569213   0.114497     50
Atil   0.090132  47.000000   0.387728     50
Ada    0.614220  -0.868918   1.160985     50

In [9]:
df.drop("Extra",axis=1,inplace=True)
df

         Salary        Age  Seniority
Kadir -0.319322  -0.793040  -1.237900
Ozge  -1.016680   2.569213   0.114497
Atil   0.090132  47.000000   0.387728
Ada    0.614220  -0.868918   1.160985

In [10]:
# axis=0 row (satır)
# axis=1 column (sütun)

In [11]:
df[df>0] # filtreleme

         Salary        Age  Seniority
Kadir       NaN        NaN        NaN
Ozge        NaN   2.569213   0.114497
Atil   0.090132  47.000000   0.387728
Ada    0.614220        NaN   1.160985

In [12]:
df

         Salary        Age  Seniority
Kadir -0.319322  -0.793040  -1.237900
Ozge  -1.016680   2.569213   0.114497
Atil   0.090132  47.000000   0.387728
Ada    0.614220  -0.868918   1.160985

In [13]:
reset_frame = df.reset_index()

In [17]:
reset_frame.iloc[0]

index           Kadir
Salary      -0.319322
Age          -0.79304
Seniority     -1.2379
Name: 0, dtype: object

In [18]:
new_index = ["Kad","Ozg","Ati","Ada"]
reset_frame["new_indices"] = new_index

In [19]:
reset_frame

   index    Salary        Age  Seniority new_indices
0  Kadir -0.319322  -0.793040  -1.237900         Kad
1   Ozge -1.016680   2.569213   0.114497         Ozg
2   Atil  0.090132  47.000000   0.387728         Ati
3    Ada  0.614220  -0.868918   1.160985         Ada

In [20]:
reset_frame.set_index("new_indices",inplace=True)

In [21]:
reset_frame

             index    Salary        Age  Seniority
new_indices
Kad          Kadir -0.319322  -0.793040  -1.237900
Ozg           Ozge -1.016680   2.569213   0.114497
Ati           Atil  0.090132  47.000000   0.387728
Ada            Ada  0.614220  -0.868918   1.160985

In [23]:
# mutli index

In [24]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]
second_index= ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [25]:
zipped_index = list(zip(first_index,second_index))

In [26]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [27]:
df

         Salary        Age  Seniority
Kadir -0.319322  -0.793040  -1.237900
Ozge  -1.016680   2.569213   0.114497
Atil   0.090132  47.000000   0.387728
Ada    0.614220  -0.868918   1.160985

In [28]:
reset_frame

             index    Salary        Age  Seniority
new_indices
Kad          Kadir -0.319322  -0.793040  -1.237900
Ozg           Ozge -1.016680   2.569213   0.114497
Ati           Atil  0.090132  47.000000   0.387728
Ada            Ada  0.614220  -0.868918   1.160985

In [29]:
new_df = reset_frame

In [30]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [31]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [33]:
sample_values = np.ones((6,2))

In [34]:
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
big_df = pd.DataFrame(sample_values,index=zipped_index,columns=["Ages","Salary"])
big_df

                    Ages  Salary
Simpson    Homer     1.0     1.0
           Bart      1.0     1.0
           Marge     1.0     1.0
South Park Cartman   1.0     1.0
           Kenny     1.0     1.0
           Kyle      1.0     1.0

In [37]:
big_df.loc["Simpson"]

       Ages  Salary
Homer   1.0     1.0
Bart    1.0     1.0
Marge   1.0     1.0

In [38]:
big_df.loc["Simpson"].loc["Bart"]

Ages      1.0
Salary    1.0
Name: Bart, dtype: float64