In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.randn(4,3)
data

array([[ 0.4522597 , -0.56548658,  1.46235477],
       [ 1.57940784, -0.02214007,  0.53509297],
       [ 0.38244827,  0.66630581,  1.33275991],
       [-0.61161289, -1.16674865,  0.59259203]])

In [9]:
df = pd.DataFrame(data,index=["Kadir","Ozge","Atil","Ada"],columns=["Salary","Age","Seniority"])
df

         Salary       Age  Seniority
Kadir  0.452260 -0.565487   1.462355
Ozge   1.579408 -0.022140   0.535093
Atil   0.382448  0.666306   1.332760
Ada   -0.611613 -1.166749   0.592592

In [20]:
df.loc["Atil"]["Age"] = 47

In [21]:
df

         Salary        Age  Seniority
Kadir  0.452260  -0.565487   1.462355
Ozge   1.579408  -0.022140   0.535093
Atil   0.382448  47.000000   1.332760
Ada   -0.611613  -1.166749   0.592592

In [22]:
df.iloc[:,1]

Kadir    -0.565487
Ozge     -0.022140
Atil     47.000000
Ada      -1.166749
Name: Age, dtype: float64