In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_excel('Veriler/6-weather.xlsx')

In [5]:
df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [8]:
df.head() # en baştaki 5 veriyi gösterir.

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [9]:
df.tail() # en sondaki 5 veriyi gösterir.

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [11]:
df.info() # DataFrame ile ilgili bilgileri getirir.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [13]:
df.describe() # DataFrame'i bize anlatır.

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [15]:
df.count() # Veri tipi ne ve kaç tane var

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [17]:
df.isna() # boş data var mı

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

#### Working with missing data

In [18]:
df = pd.read_excel('Veriler/6-weatherna.xlsx')
df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [19]:
df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   8 non-null      float64
 1   New York   8 non-null      float64
 2   Amsterdam  8 non-null      float64
 3   Paris      6 non-null      float64
dtypes: float64(4)
memory usage: 420.0 bytes

In [21]:
df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [22]:
df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [23]:
df.dropna()

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [25]:
df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [26]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [27]:
df.drop("Paris",axis=1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [28]:
df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [29]:
df.fillna(df.mean())

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [31]:
df["Çorum"]= df["Paris"]

In [35]:
df.drop("Paris", axis=1)

   Istanbul  New York  Amsterdam  Çorum
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [36]:
df = pd.read_csv('Veriler/6-employee.csv')

In [41]:
df.head()

  Department Employee  Salary  Experience           City
0  Marketing    Emp_1   53483           1       New York
1      Sales    Emp_2   78555           8         Austin
2    Finance    Emp_3   47159           3         Austin
3      Sales    Emp_4  110077           3  San Francisco
4      Sales    Emp_5   65920           1       New York

In [42]:
df.describe()

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  50 non-null     object
 1   Employee    50 non-null     object
 2   Salary      50 non-null     int64
 3   Experience  50 non-null     int64
 4   City        50 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [58]:
df[(df["City"]=="New York")&(df["Experience"]>5)&(df["Department"]=="HR")]["Salary"].mean()
# NewYork'da olan, tecrübesi 5 yıldan fazla olan, HR departmanında olan insanların maaşları ortalaması.

np.float64(88939.0)

In [64]:
df_grouped=df.groupby('Department')

In [65]:
df_grouped.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

In [66]:
df_grouped.count()

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [75]:
df.groupby('City')["Salary"].mean()

City
Austin           81216.000000
Chicago          76869.363636
New York         70484.133333
San Francisco    87144.727273
Name: Salary, dtype: float64